server:
  port: ${PORT:8185}

spring :
  application :
    name : AUTH-SERVICE

  # for log color
  output:
    ansi:
      enabled: always

  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true
    properties :
      hibernate :
        format_sql : true

  datasource :
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:auth_db}?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:mysql}
    driver-class-name : com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/insa-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:${DISCOVERY_SERVER_PORT:8060}/eureka/

#related to Spring Boot's actuator and management endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# for swagger
springdoc:
  swagger-ui:
    oauth:
      client-id: saas-hrms-client
      client-secret: M6Fc3ogo5m9NUOzbwvHffotonOCxPa7l

logging:
  level:
    org.springframework.security: trace

keycloak:
  realm: insa-realm
  auth-server-url: http://localhost:8080
  client-id: saas-hrms-client
  client-secret: M6Fc3ogo5m9NUOzbwvHffotonOCxPa7l
  grant-type: password
  admin-username: admin
  admin-password: Admin@123


tenant-service:
  base-url: ${TENANT_SERVICE_BASE_URL:http://localhost:8181}