version: '3.8'

services:
  # MySQL Database
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: tenant_db
    ports:
      - "3306:3306"
    volumes:
      - ./init-multiple-databases.sql:/docker-entrypoint-initdb.d/init-multiple-databases.sql
    networks:
      - hrms-network

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak
    ports:
      - "8282:8282"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DATABASE_VENDOR: mysql
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: mysql
      DATABASE_HOST: mysql-db
      DATABASE_NAME: keycloak_db
      PORT: 8282
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - ./keycloak-25.0.1/conf/keycloak.conf:/opt/keycloak/conf/keycloak.conf
    depends_on:
      - mysql-db
    command: start-dev
    networks:
      - hrms-network

  # Discovery Server
  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    image: discovery-server:latest
    container_name: discovery-server
    ports:
      - "8060:8060"
    environment:
      - PORT=8060
      - HOSTNAME=discovery-server
    networks:
      - hrms-network
    volumes:
      - ./discovery-server/target/discovery-server.jar:/app/discovery-server.jar

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8060
    depends_on:
      - discovery-server
    networks:
      - hrms-network
    volumes:
      - ./api-gateway/target/api-gateway.jar:/app/api-gateway.jar

  # Tenant Service
  tenant-service:
    build:
      context: ./tenant-service
      dockerfile: Dockerfile
    image: tenant-service:latest
    container_name: tenant-service
    ports:
      - "8181:8181"
    environment:
      - PORT=8181
      - DATABASE_HOST=mysql-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=tenant_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mysql
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8060
    depends_on:
      - discovery-server
      - mysql-db
    networks:
      - hrms-network
    volumes:
      - ./tenant-service/target/tenant-service.jar:/app/tenant-service.jar

  # Employee Service
  employee-service:
    build:
      context: ./employee-service
      dockerfile: Dockerfile
    image: employee-service:latest
    container_name: employee-service
    ports:
      - "8180:8180"
    environment:
      - PORT=8180
      - DATABASE_HOST=mysql-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=employee_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mysql
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8060
      - TENANT_SERVICE_BASE_URL=http://tenant-service:8181
    depends_on:
      - discovery-server
      - mysql-db
    networks:
      - hrms-network
    volumes:
      - ./employee-service/target/employee-service.jar:/app/employee-service.jar

  # Leave Service
  leave-service:
    build:
      context: ./leave-service
      dockerfile: Dockerfile
    image: leave-service:latest
    container_name: leave-service
    ports:
      - "8184:8184"
    environment:
      - PORT=8184
      - DATABASE_HOST=mysql-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=leave_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mysql
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8060
      - TENANT_SERVICE_BASE_URL=http://tenant-service:8181
      - EMPLOYEE_SERVICE_BASE_URL=http://employee-service:8180
    depends_on:
      - discovery-server
      - mysql-db
    networks:
      - hrms-network
    volumes:
      - ./leave-service/target/leave-service.jar:/app/leave-service.jar

  # Recruitment Service
  recruitment-service:
    build:
      context: ./recruitment-service
      dockerfile: Dockerfile
    image: recruitment-service:latest
    container_name: recruitment-service
    ports:
      - "8182:8182"
    environment:
      - PORT=8182
      - DATABASE_HOST=mysql-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=recruitment_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mysql
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8060
      - TENANT_SERVICE_BASE_URL=http://tenant-service:8181
      - EMPLOYEE_SERVICE_BASE_URL=http://employee-service:8180
    depends_on:
      - discovery-server
      - tenant-service
      - mysql-db
    networks:
      - hrms-network
    volumes:
      - ./recruitment-service/target/recruitment-service.jar:/app/recruitment-service.jar

  # Training Service
  training-service:
    build:
      context: ./training-service
      dockerfile: Dockerfile
    image: training-service:latest
    container_name: training-service
    ports:
      - "8183:8183"
    environment:
      - PORT=8183
      - DATABASE_HOST=mysql-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=training_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mysql
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8060
      - TENANT_SERVICE_BASE_URL=http://tenant-service:8181
      - EMPLOYEE_SERVICE_BASE_URL=http://employee-service:8180
      - LEAVE_SERVICE_BASE_URL=http://leave-service:8184
    depends_on:
      - discovery-server
      - tenant-service
      - mysql-db
    networks:
      - hrms-network
    volumes:
      - ./training-service/target/training-service.jar:/app/training-service.jar

  # HR Planning Service
  hr_planning-service:
    build:
      context: ./hr_planning-service
      dockerfile: Dockerfile
    image: hr_planning-service:latest
    container_name: hr_planning-service
    ports:
      - "8186:8186"
    environment:
      - PORT=8186
      - DATABASE_HOST=mysql-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=hr-planning_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mysql
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8060
      - TENANT_SERVICE_BASE_URL=http://tenant-service:8181
      - LEAVE_SERVICE_BASE_URL=http://leave-service:8184
    depends_on:
      - discovery-server
      - tenant-service
      - mysql-db
    networks:
      - hrms-network
    volumes:
      - ./hr_planning-service/target/hr_planning-service.jar:/app/hr_planning-service.jar

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "8185:8185"
    environment:
      - PORT=8185
      - DATABASE_HOST=mysql-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=auth_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mysql
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8060
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8282
      - TENANT_SERVICE_BASE_URL=http://tenant-service:8181
    depends_on:
      - discovery-server
      - mysql-db
      - keycloak
      - tenant-service
    networks:
      - hrms-network
    volumes:
      - ./auth-service/target/auth-service.jar:/app/auth-service.jar

networks:
  hrms-network:
    driver: bridge