server:
  port: 8761

spring :
  application :
    name : DISCOVERY-SERVER

  output:
    ansi:
      enabled: always

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761}/eureka/

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always