server:
  port: 8183

spring:
  application:
    name: TRAINING-SERVICE

  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8282}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/training_db}?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

springdoc:
  swagger-ui:
    oauth:
      client-id: ${keycloak.client-id}
      client-secret: ${keycloak.client-secret}

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
  realm: saas-realm
  client-id: saas-client
  client-secret: 7FsOMKTT2Q8uKb6FkulJHSwQfAAEKhoT
