server :
  port : ${PORT:8186}

spring :
  application :
    name : HR_PLANNING-SERVICE

  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true
    properties :
      hibernate :
        format_sql : true

  datasource :
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:hr-planning_db}?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:mysql}
    driver-class-name : com.mysql.cj.jdbc.Driver


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:${DISCOVERY_SERVER_PORT:8060}/eureka/

#actuator and management endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

tenant-service:
  base-url: ${TENANT_SERVICE_BASE_URL:http://localhost:8181}
leave-service:
  base-url: ${Leave_SERVICE_BASE_URL:http://localhost:8184}
