server :
  port : 8186

spring :
  application :
    name : HR_PLANNING-SERVICE

  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8282}

  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true
    properties :
      hibernate :
        format_sql : true

  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/hr_planning_db}?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    oauth:
      client-id: ${keycloak.client-id}
      client-secret: ${keycloak.client-secret}

